### ISSUE TITLE
Can't compile on Arduino 1.8.14

### ISSUE THREAD

**Issue by Calimerorulez** [shortbloke/Broadband_Usage_Display#3]
Hi Martin,

Thanks for the cool project!

I'm trying to compile the source of the fixed speed version, but I can't seem to get it to work:

The sketch errors on:
```
// Get callbacks from creating a handler for each of the OID
  callbackInOctets = snmp.addCounter32Handler(oidInOctets, &inOctets);
  callbackOutOctets = snmp.addCounter32Handler(oidOutOctets, &outOctets);
  callbackUptime = snmp.addTimestampHandler(oidUptime, &uptime);
```

with the following errors:

```
C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino: In function 'void setup()':
SNMP-speed:109:69: error: no matching function for call to 'SNMPManager::addCounter32Handler(char*&, unsigned int*)'
   callbackInOctets = snmp.addCounter32Handler(oidInOctets, &inOctets);
                                                                     ^
C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino:109:69: note: candidate is:
In file included from C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino:5:0:
C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager\src/Arduino_SNMP_Manager.h:430:16: note: ValueCallback* SNMPManager::addCounter32Handler(IPAddress, const char*, uint32_t*)
 ValueCallback *SNMPManager::addCounter32Handler(IPAddress ip, const char *oid, uint32_t *value)
                ^
C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager\src/Arduino_SNMP_Manager.h:430:16: note:   candidate expects 3 arguments, 2 provided
SNMP-speed:110:72: error: no matching function for call to 'SNMPManager::addCounter32Handler(char*&, unsigned int*)'
   callbackOutOctets = snmp.addCounter32Handler(oidOutOctets, &outOctets);
                                                                        ^
C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino:110:72: note: candidate is:
In file included from C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino:5:0:
C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager\src/Arduino_SNMP_Manager.h:430:16: note: ValueCallback* SNMPManager::addCounter32Handler(IPAddress, const char*, uint32_t*)
 ValueCallback *SNMPManager::addCounter32Handler(IPAddress ip, const char *oid, uint32_t *value)
                ^
C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager\src/Arduino_SNMP_Manager.h:430:16: note:   candidate expects 3 arguments, 2 provided
SNMP-speed:111:63: error: no matching function for call to 'SNMPManager::addTimestampHandler(char*&, int*)'
   callbackUptime = snmp.addTimestampHandler(oidUptime, &uptime);
                                                               ^
C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino:111:63: note: candidate is:
In file included from C:\Users\pat\Documents\Arduino\SNMP-speed\SNMP-speed.ino:5:0:
C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager\src/Arduino_SNMP_Manager.h:397:16: note: ValueCallback* SNMPManager::addTimestampHandler(IPAddress, const char*, int*)
 ValueCallback *SNMPManager::addTimestampHandler(IPAddress ip, const char *oid, int *value)
                ^
C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager\src/Arduino_SNMP_Manager.h:397:16: note:   candidate expects 3 arguments, 2 provided
exit status 1
no matching function for call to 'SNMPManager::addCounter32Handler(char*&, unsigned int*)'
```

Should I alter the sketch so the functions get the 'router' IP address passed to them, as the first argument/parameter? It sucessfully compiles then, but I don't know if it will work yet.

I hope you can help.

Regards,
Patrick

**Comment by shortbloke** [comment]
Sorry, yes the example hadn't been updated following the changes I made to the library where you need to pass the IP address as the first argument, necessary to allow the library to make calls to multiple devices. 

Example updated. Thanks,
